pipeline {
    agent any

    environment{
        RELEASE = '0.0.1'
    }

    stages{
        stage('Build'){
            environment {
                LOG_LEVEL = 'info'
            }

            steps{
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            } 
        }
        stage('Test'){
            steps{
                echo "Testing. I can see ${RELEASE} but not log level"
            }
        }
        stage('Deploy'){
            input{
                message 'Deploy?'
                ok 'Do it'
                parameters{
                    string(name: 'TARGET_ENVIRONMENT', default: 'PROD', description: 'Target deployment environment')
                }
            }

            steps{
                echo "Deployin release ${RELEASE} to ${TARGET_ENVIRONMENT}"
            }
        }

    }
}