pipeline{
    agent any

    environment {
        VERSION = sh(script: 'cd 01/solution && npx -c \'echo $npm_package_version\'',returnStdout: true).trim()
        VERSION_RC = 'rc.2'
    }

    stages{
        stage('Build'){
            steps{
                echo "Building version ${VERSION} with suffic ${VERSION_RC}"
                sh 'Building version ${VERSION} with suffic ${VERSION_RC}'
                sh'''
                npm install
                npm run build
                '''
            }

        }

        stage('Unit Test'){
            steps{
                sh 'npm test'
            }

        }
    }
}