library identifier: 'jenkin-sessions-library@main', retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/calamarzo/jenkins-sessions-library.git'])

pipeline{
    agent any

    stages{
        stage('Audit Tools'){
            steps{
                auditTools()
            }
        }
    }
}